# Generated by Django 3.2.7 on 2022-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220225_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gvs',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Список домов Северного и Южного сетевых районов, в которых отсутствует ГВС'},
        ),
        migrations.AlterField(
            model_name='gvs',
            name='date_connect',
            field=models.DateField(verbose_name='Ориентировочная дата устранения'),
        ),
        migrations.AlterField(
            model_name='gvs',
            name='date_disconnect',
            field=models.DateField(verbose_name='Дата отключения'),
        ),
    ]
