# Generated by Django 3.2.7 on 2022-03-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220225_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gvs',
            options={'ordering': ['id', 'region', 'street', 'build'], 'verbose_name': 'Элемент списка', 'verbose_name_plural': 'Список домов Северного и Южного сетевых районов, в которых отсутствует ГВС'},
        ),
    ]
